### ISSUE TITLE
The number of SNPs in at least one of the samples does not match the number of SNPs in the map file

### ISSUE THREAD

**Issue by jianggl2000** [roohy/iLASH#1]
**Updates:** 
Have this issue for some ped/map files generated by PLINK.

> terminate called after throwing an instance of 'DimensionException'
>   what():  The number of SNPs in at least one of the samples does not match the number of SNPs in the map file

**Comment by roohy** [comment]
A standard map/ped pair of files would always share the same number of SNPs between them. Getting this error means either one of the files is corrupted, or the two did not belong to the same data in the first place.
